---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
    name: efk-elasticsearch-template
objects:
    - kind: Service
      apiVersion: v1
      metadata:
          name: elasticsearch
          namespace: "${NAMESPACE}"
          labels:
              app: elasticsearch
      spec:
          selector:
              app: elasticsearch
          clusterIP: None
          ports:
              - port: 9200
                name: rest
              - port: 9300
                name: inter-node
    - kind: StatefulSet
      apiVersion: apps/v1
      metadata:
          name: es-cluster
          namespace: "${NAMESPACE}"
          labels:
              "app.kubernetes.io/part-of": efk-stack
      spec:
          serviceName: elasticsearch
          replicas: 3
          selector:
              matchLabels:
                  app: elasticsearch
          template:
              metadata:
                  labels:
                      app: elasticsearch
              spec:
                  containers:
                      - name: elasticsearch
                        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
                        resources:
                            limits:
                                cpu: 100m
                            requests:
                                cpu: 10m
                        ports:
                            - name: rest
                              containerPort: 9200
                              protocol: TCP
                            - name: inter-node
                              containerPort: 9300
                              protocol: TCP
                        volumeMounts:
                            - name: data
                              mountPath: /usr/share/elasticsearch/data
                        env:
                            - name: cluster.name
                              value: elasticsearch
                            - name: node.name
                              valueFrom:
                                  fieldRef:
                                      fieldPath: metadata.name
                            - name: discovery.seed_hosts
                              value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
                            - name: cluster.initial_master_nodes
                              value: "es-cluster-0,es-cluster-1,es-cluster-2"
                            - name: ES_JAVA_OPTS
                              value: "-Xms512m -Xmx512m"
                            - name: xpack.security.enabled
                              value: "false"
          volumeClaimTemplates:
              - metadata:
                    name: data
                    labels:
                        app: elasticsearch
                spec:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: netapp-file-standard
                    resources:
                        requests:
                            storage: "${ELASTICSEARCH_STORAGE_REQUEST}"
parameters:
    - name: NAMESPACE
      description: Namespace to install EFK stack
      displayName: Namespace
      required: true
    - name: ELASTICSEARCH_STORAGE_REQUEST
      description: Requested Storage per pod (Gi, Mi, Ki)
      displayName: Storage Request
      value: 1Gi
